services:
  postgres:
    image: postgres:17.5
    container_name: pg-4kgbbad-1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-4kgbbad-volume:/var/lib/postgresql/data
    networks:
      - pg-4kgbbad-net

  cauth-app:
    build: .
    container_name: cauth_app
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - pg-4kgbbad-net
volumes:
  pg-4kgbbad-volume:

networks:
  pg-4kgbbad-net:
    name: pg-4kgbbad-net

