services:

  app:
    build: .
    container_name: central
    networks:
      - 4kgbbad-net
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: cauth
      SPRING_DATASOURCE_PASSWORD: 1234567
      LIQUIBASE_URL: jdbc:postgresql://pg-4kgbbad-5:5432/postgres
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  pg-4kgbbad-vol:
    name: pg-4kgbbad-vol

networks:
  4kgbbad-net:
    external: true
