services:
  postgres:
    image: 'postgres:17.5'
    container_name: datasource-4KGBBAD
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  cauth-app:
    build: .
    container_name: cauth_app
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
volumes:
  pgdata: