spring:
  application:
    name: Central Authentication Service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/centralauthdb
    username: centraldb
    password: pieis18235312+
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/central-auth-changelog-master.xml

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

###############################
#         Logging             #
###############################

logging:
  level:
    root: DEBUG
    com.baerchen: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: TRACE
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client.endpoint: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.web.client.RestTemplate: TRACE


# expose /actuator/httptrace, etc., to get recent request traces (max 100 by default):

management:
  endpoints:
    web:
      exposure:
        include: "*"
