DROP ROLE IF EXISTS ${DATASOURCE_USERNAME};

CREATE ROLE ${DATASOURCE_USERNAME} LOGIN PASSWORD '${DATASOURCE_PASSWORD}';

DROP SCHEMA IF EXISTS ${ENV_PREFIX}_${DATASOURCE_SCHEMA} CASCADE;

CREATE SCHEMA ${ENV_PREFIX}_${DATASOURCE_SCHEMA} AUTHORIZATION ${DATASOURCE_USERNAME};

REVOKE ALL ON SCHEMA ${ENV_PREFIX}_${DATASOURCE_SCHEMA} FROM PUBLIC;

GRANT USAGE ON SCHEMA ${ENV_PREFIX}_${DATASOURCE_SCHEMA} TO ${DATASOURCE_USERNAME};
GRANT CREATE ON SCHEMA ${ENV_PREFIX}_${DATASOURCE_SCHEMA} TO ${DATASOURCE_USERNAME};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${ENV_PREFIX}_${DATASOURCE_SCHEMA}
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DATASOURCE_USERNAME};
